### ISSUE TITLE
Getting "400 Client Error: Bad Request" from fetch_creds

### ISSUE THREAD

**Issue by graham-m-dunn** [wheniwork/keyme#3]
```Traceback (most recent call last):
  File "/usr/local/bin/fetch_creds", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1053, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 63, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/keyme/cli/fetch_creds.py", line 177, in login
    {}
  File "/usr/local/lib/python2.7/site-packages/keyme/cli/fetch_creds.py", line 52, in generate_keys
    principal=principal).key()
  File "/usr/local/lib/python2.7/site-packages/keyme/__init__.py", line 42, in key
    self.session = self.login_to_google()
  File "/usr/local/lib/python2.7/site-packages/keyme/__init__.py", line 166, in login_to_google
    google_session.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 851, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request

Is the AWS spid the account number? ie, if my default role is "arn:aws:iam::xxxxxxxxxxxx:role/ITAdmin", is the spid xxxxxxxxxxxx?

**Comment by moos3** [comment]
yes its the account number that shows up in the ARN of the SP you setup in aws's console.
